### ISSUE TITLE
Extend externaltask handler for async processing scenarios

### ISSUE THREAD

**Issue by phactum-at** [stephanpelikan/camunda-externaltask-handler#1]
The current implementation is a replacement for Java delegate implemenation, expression delegates or expressions.

Doing asynchronous communication Camunda suggest to use this pattern:
<img src="https://user-images.githubusercontent.com/13745125/116509480-a8dbd380-a8c3-11eb-9d97-89b724806389.png" alt="async" width="500"/>

But on the other hand Camunda always tells us that details of the technical implementation should not be part of the business process since it is about business requirements and from that perspective it does not matter whether a bounded system provides a synchronous or an asynchronous API. So it should look like this:
<img src="https://user-images.githubusercontent.com/13745125/116509810-33243780-a8c4-11eb-91be-ab3b8e1223a9.png" alt="async2" width="350"/>

Using two message flows in different directions might be a hint to the reader that async communication is done. If it's not obviously which part is the caller then only one message flow should be used to indicate the initiator of this communication:
<img src="https://user-images.githubusercontent.com/13745125/116510711-9fec0180-a8c5-11eb-9c18-b091a905c13d.png" alt="async3" width="400"/>

Since the external task implemenations is a wait state in terms of Camunda's workflow processing it's predicted to use it for hidden asynchronous communication. The external task handler should provide an API which supports this pattern.

**Comment by stephanpelikan** [comment]
Change to fluent API as part of implementation of #2
